### ISSUE TITLE
imPar error in tokenVisitAliases

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#505]
tokenVisitAliases have to be a column cell array and not a row. See the example that crashes the 1.5.1 and 1.6.0.

imPar.studyID = 'Dialysis_Study'; 
imPar.AnalysisRoot = 'C:\Users\USER\Desktop\RIPC3\'; 
imPar.RawRoot = 'C:\Users\USER\Desktop\RIPC3\'; 
imPar.folderHierarchy = {'^(.*\d{2})$' '^.*(post|pre)$' '^(ASL|DSC|M0|MPRAGE).*$'} 
imPar.tokenOrdering = [ 1 2 0 3]; 
imPar.tokenVisitAliases = {'^pre','_1','^post','_2'}; 
imPar.tokenSessionAliases = {}; 
imPar.tokenScanAliases = {'^ASL$', 'ASL4D';'^DSC$','DSC4D';'^M0$','M0';'^MPRAGE$','T1'}; 
imPar.bMatchDirectories = true; 
ExploreASL_Import(imPar) 

### Release change
Minor bug - allow Token Aliases in import to be row vectors as well.

**Comment by MichaelStritt** [comment]
Potentially fixed here: 39a285c 
At least that's my take on it 👍

**Comment by jan-petr** [comment]
> Potentially fixed here: [39a285c](https://github.com/ExploreASL/ExploreASL/commit/39a285c74df98b0c25fe06722c65cbf4a1cc9e8a)
> At least that's my take on it

That didn't solve that. So had to add a simple fix to both Legacy and BIDS import.

**Comment by jan-petr** [comment]
> tokenVisitAliases have to be a column cell array and not a row. See the example that crashes the 1.5.1 and 1.6.0.
> 
> imPar.studyID = 'Dialysis_Study';
> imPar.AnalysisRoot = 'C:\Users\USER\Desktop\RIPC3';
> imPar.RawRoot = 'C:\Users\USER\Desktop\RIPC3';
> imPar.folderHierarchy = {'^(._\d{2})$' '^._(post|pre)$' '^(ASL|DSC|M0|MPRAGE).*$'}
> imPar.tokenOrdering = [ 1 2 0 3];
> imPar.tokenVisitAliases = {'^pre','_1','^post','_2'};
> imPar.tokenSessionAliases = {};
> imPar.tokenScanAliases = {'^ASL$', 'ASL4D';'^DSC$','DSC4D';'^M0$','M0';'^MPRAGE$','T1'};
> imPar.bMatchDirectories = true;
> ExploreASL_Import(imPar)

### Release change
Minor bug - allow Token Aliases in import to be row vectors as well.

**Comment by MichaelStritt** [comment]
> 
> 
> > Potentially fixed here: [39a285c](https://github.com/ExploreASL/ExploreASL/commit/39a285c74df98b0c25fe06722c65cbf4a1cc9e8a)
> > At least that's my take on it
> 
> That didn't solve that. So had to add a simple fix to both Legacy and BIDS import.

Oh yes, my fix only works within ImportConfig. I just thought it would help to show what I'm doing there :)
